install:
	python -m pip install -r requirements.txt || python3 -m pip install -r requirements.txt

run:
	python -m uvicorn "main:application" || python3 -m uvicorn "main:application"

test:
	python -m pytest ../tests/test_homework_1.py || python3 -m pytest ../tests/test_homework_1.py
